printf "\n"
printf "====================================================="
printf "\n"
printf "==================== CRUD CREATE ===================="
printf "\n"
printf "====================================================="
printf "\n"
printf "\n"
bash ./CRUD/tests/create.sh
printf "\n"
printf "\n"
printf "====================================================="
printf "\n"
printf "==================== CRUD POST ======================"
printf "\n"
printf "====================================================="
printf "\n"
printf "\n"
bash ./CRUD/tests/post.sh
printf "\n"
printf "\n"
printf "====================================================="
printf "\n"
printf "==================== CRUD DELETE ===================="
printf "\n"
printf "====================================================="
printf "\n"
printf "\n"
bash ./CRUD/tests/delete.sh
printf "\n"
printf "\n"
printf "====================================================="
printf "\n"
printf "==================== CRUD UPDATE ===================="
printf "\n"
printf "====================================================="
printf "\n"
printf "\n"
bash ./CRUD/tests/update.sh
printf "\n"
printf "====================================================="
printf "\n"
printf "=================== USERS TABLE ====================="
printf "\n"
printf "====================================================="
printf "\n"
printf "\n"
bash ./tables/tests/users.test.sh
printf "\n"
printf "====================================================="
printf "\n"
printf "================= CUSTOMERS TABLE ==================="
printf "\n"
printf "====================================================="
printf "\n"
printf "\n"
bash ./tables/tests/customers.test.sh
# bash ./tables/tests/trips.test.sh