#! /bin/bash
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}====================${NC} ${GREEN}CRUD CREATE${NC} ${BLUE}====================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./CRUD/tests/create.sh
printf "\n"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}====================${NC} ${GREEN}CRUD POST${NC} ${BLUE}======================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./CRUD/tests/post.sh
printf "\n"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}====================${NC} ${GREEN}CRUD DELETE${NC} ${BLUE}====================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./CRUD/tests/delete.sh
printf "\n"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}====================${NC} ${GREEN}CRUD UPDATE${NC} ${BLUE}====================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./CRUD/tests/update.sh
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}===================${NC} ${GREEN}USERS TABLE${NC} ${BLUE}=====================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./tables/tests/users.test.sh
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}=================${NC} ${GREEN}CUSTOMERS TABLE${NC} ${BLUE}===================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./tables/tests/customers.test.sh
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}===================${NC} ${GREEN}TRIPS TABLE${NC} ${BLUE}=====================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./tables/tests/trips.test.sh
printf "\n"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}===================${NC} ${GREEN}HOST TABLE${NC} ${BLUE}======================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./tables/tests/host.test.sh
printf "\n"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}==============${NC} ${GREEN}TRANSPORTATION TABLE${NC} ${BLUE}=================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./tables/tests/transportation.test.sh
printf "\n"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "${BLUE}================${NC} ${GREEN}ACTIVITIES TABLE${NC} ${BLUE}===================${NC}"
printf "\n"
printf "${BLUE}=====================================================${NC}"
printf "\n"
printf "\n"
bash ./tables/tests/activities.test.sh
printf "\n"

